### ISSUE TITLE
无法登陆获取data

### ISSUE THREAD

**Issue by zerone0x** [shengqiangzhang/leetcode-revise#2]
一直显示用户或密码错误。

**Comment by shengqiangzhang** [comment]
@zerone0x 这边运行正常，你是改动了什么代码么？

**Comment by shengqiangzhang** [comment]
@zerone0x 这边运行正常，你是改动了什么代码么？建议你登录一下leetcode中国官方网站，确保账号密码是正确的。

**Comment by zerone0x** [comment]
@shengqiangzhang 没有改代码。这边中国leetcode网站可以正常登录。前三次用邮箱都是账号密码错误。把邮箱换成用户名依旧失败。

前三次:<img width="750" alt="image" src="https://user-images.githubusercontent.com/39543393/159854064-1c657c06-6d92-434a-afbb-7cf326edb834.png">

最后一次:<img width="783" alt="image" src="https://user-images.githubusercontent.com/39543393/159854009-fcc49943-34a4-410f-bcfa-b02b064a11cb.png">

**Comment by shengqiangzhang** [comment]
@zerone0x 前三次你是用邮箱登录的，但是你输入的格式不对，因为你看提示就知道了，提示为“list index out of range”，输入格式为 `python3 leetcode.py 3257179914@qq.com 密码` 。请注意`python3` `leetcode.py` `3257179914@qq.com` `密码`之间均有空格 。

最后一次，使用用户名是无法登录的，因此建议你检查你的输入格式。

**Comment by shengqiangzhang** [comment]
@zerone0x 建议你在本地运行试试先把，可能是你github actions的问题。
先确保本地能运行通过。

**Comment by shengqiangzhang** [comment]
@zerone0x 大概发现原因了，前三次你是用邮箱登录的，但是无法解析输入的格式，我怀疑可能是github actions脚本的问题。
因为你看提示就知道了，提示为“list index out of range”，输入格式为 python3 leetcode.py 3257179914@qq.com 密码 。
请注意python3 leetcode.py 3257179914@qq.com 密码之间均有空格 。

建议你在本地自己先运行下，看看是否能够登录成功，如果可以的话，说明该程序还是有点问题的，可能对于github actions的适配不是很好。

我自己运行的图：
![image](https://user-images.githubusercontent.com/28225826/159857681-070f6ce1-79a3-49d8-a498-ce65fc08db11.png)

你提供的图：
![image](https://user-images.githubusercontent.com/28225826/159857714-001a20c1-d5ef-4408-b5c8-8790bff17fa9.png)

你的脚本可能存在问题，导致无法解析输入内容了。

**Comment by zerone0x** [comment]
> @zerone0x 大概发现原因了，前三次你是用邮箱登录的，但是无法解析输入的格式，我怀疑可能是github actions脚本的问题。 因为你看提示就知道了，提示为“list index out of range”，输入格式为 python3 [leetcode.py](http://leetcode.py) [3257179914@qq.com](mailto:3257179914@qq.com) 密码 。 请注意python3 [leetcode.py](http://leetcode.py) [3257179914@qq.com](mailto:3257179914@qq.com) 密码之间均有空格 。
> 
> 建议你在本地自己先运行下，看看是否能够登录成功，如果可以的话，说明该程序还是有点问题的，可能对于github actions的适配不是很好。
> 
> 我自己运行的图： ![image](https://user-images.githubusercontent.com/28225826/159857681-070f6ce1-79a3-49d8-a498-ce65fc08db11.png)
> 
> 你提供的图： ![image](https://user-images.githubusercontent.com/28225826/159857714-001a20c1-d5ef-4408-b5c8-8790bff17fa9.png)
> 
> 你的脚本可能存在问题，导致无法解析输入内容了。

找到原因了。密码中有&。
